apiVersion: v1
kind: Service
metadata:
  name: {{ include "handicap.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "handicap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "handicap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  ports:
    - name: rest
      port: {{ .Values.controller.rest.port }}
      targetPort: rest
      protocol: TCP
    - name: grpc
      port: {{ .Values.controller.grpc.port }}
      targetPort: grpc
      protocol: TCP
