{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "handicap.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "handicap.labels" . | nindent 4 }}
{{- end -}}
